### ISSUE TITLE
No Such File error

### ISSUE THREAD

**Issue by OrangeBlenders** [Djdefrag/RealScaler#6]
![Screenshot_20230824_094545_RVNC Viewer](https://github.com/Djdefrag/RealScaler/assets/105076165/0af8e713-8623-4cac-a8f6-4e423f5a0502)

**Comment by Djdefrag** [comment]
Hi my friend, 

it seems that RealScaler can t find the video frame number 129912. 

If I were to assume the problem, I think the app failed to write that upscaled video frame as a file because the disk space ran out.

Assuming that each upscaled frame in .png format weighs 5Mb, 129k frames would take up more than 600Gb on the disk.

I recommend you use Image output .jpg, which compared to .png weighs ~5 times less. Or break the video into several parts :)

**Comment by OrangeBlenders** [comment]
This is exactly it. Thank you.
